POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "test",
  "password": "123"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "testEmail",
"password": "test123"
}